module.exports.Decode_Chars = [
  { CH: "A", S_CH: "U4&P" },
  { CH: "B", S_CH: "$L@F" },
  { CH: "C", S_CH: "M*F9" },
  { CH: "D", S_CH: "P^3*" },
  { CH: "E", S_CH: "MX%2" },
  { CH: "F", S_CH: "D$R%" },
  { CH: "G", S_CH: "FS%4" },
  { CH: "H", S_CH: "H7E%" },
  { CH: "I", S_CH: ">VH7" },
  { CH: "J", S_CH: ";CB4" },
  { CH: "K", S_CH: "XQ?(" },
  { CH: "L", S_CH: "N1$W" },
  { CH: "M", S_CH: ">E6I" },
  { CH: "N", S_CH: "I7G&" },
  { CH: "O", S_CH: "2FùZ" },
  { CH: "P", S_CH: "*RY5" },
  { CH: "Q", S_CH: "NU6@" },
  { CH: "R", S_CH: "TR5%" },
  { CH: "S", S_CH: "L%N0" },
  { CH: "T", S_CH: "!J1F" },
  { CH: "U", S_CH: "6*IZ" },
  { CH: "V", S_CH: "R4X%" },
  { CH: "W", S_CH: "H$F3" },
  { CH: "X", S_CH: "H9%E" },
  { CH: "Y", S_CH: "SX1*" },
  { CH: "Z", S_CH: "J$V&" },
  { CH: " ", S_CH: "RD^X" },
  { CH: ".", S_CH: "D?T6" },
  { CH: ",", S_CH: "S!L1" },
  { CH: "?", S_CH: "K?^1" },
  { CH: "!", S_CH: "8J3#" },
  { CH: "0", S_CH: "0$01" },
  { CH: "1", S_CH: "0$02" },
  { CH: "2", S_CH: "0$03" },
  { CH: "3", S_CH: "0$11" },
  { CH: "4", S_CH: "0$21" },
  { CH: "5", S_CH: "0$31" },
  { CH: "6", S_CH: "1$11" },
  { CH: "7", S_CH: "2$21" },
  { CH: "8", S_CH: "3$31" },
  { CH: "9", S_CH: "1%11" },
];

module.exports.splitSymbol = "#&";
